# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: ECWUUUUU Homepage
    url: https://www.ecwuuuuu.com
  - name: ECWU.xyz
    url: https://ecwu.xyz
  - name: PHOTO Site
    url: https://foto.ecwuuuuu.com
  - name: Tiny Tiny RSS
    url: https://rss.ecwu.xyz
  - name: RSSHub
    url: https://r.ecwu.xyz
  - name: BitWarden
    url: https://k.ecwu.xyz

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: up.ecwuuuuu.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ECWU Status
  introTitle: "Build with **Upptime**, powered entirely by GitHub."
  introMessage: TBA
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/ecwu

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
